### ISSUE TITLE
How to make wifi work

### ISSUE THREAD

**Issue by phumynice** [xkhoir/Lenovo-310-14ISK-Hackintosh-EFI-OpenCore#1]
I'm using AirportItlwm.kext or tlwm.kext but wifi not work
Please support for me.

**Comment by xkhoir** [comment]
hi @phumynice 

what wifi card are you using?

if you use same laptop and the wifi card is intel AC 3165, then you just have to copy and paste the Airportitlwm.kext into the OC kext folder.

And then 
1. cleansnapshot using propertree
2. restart
At OC boot picker choose Clean NVRAM

done (Sorry my bad english)
