### ISSUE TITLE
Battery is not working

### ISSUE THREAD

**Issue by vinays1999** [xkhoir/Lenovo-310-14ISK-Hackintosh-EFI-OpenCore#3]
Hello, I am using Lenovo ideapad 310, 15isk. I applied your EFI. everything is working except battery. I tried to patch battery in DSDT. but got some args errors.

[DSDT.aml.zip](https://github.com/xkhoir/Lenovo-310-14ISK-Hackintosh-EFI-OpenCore/files/6362744/DSDT.aml.zip)

**Comment by vinays1999** [comment]
more issues....

Brightness key is not working..
Cmd and alt keys swapped..

Can you help me to create perfect EFI for my laptop??

**Comment by xkhoir** [comment]
1. Fix Battery Patch 
before patching the battery in dsdt
You have to decompile dsdt.aml to dsdt.dsl (this is important) and edit it on maciasl. and make sure the dsdt is clean from errors, and able to patch it. and when it's finished do the opposite by compiling dsdt.dsl to dsdt.aml 

if you've got same Laptop model and already upgraded to lastest bios (LENOVO Insyde 0XCN45WW) you can just simply use the my dsdt in EFI -> OC -> ACPI -> dsdt.aml

2. Fix Brightness Key F11 & F12
If you are in big sur. Just try entering system preferences -> keyboard -> shortcuts -> display. change it to the f11 & f12 button according to the image below. this is work with fn + f11 for decrease and fn + f12 for increase.
![gambar](https://user-images.githubusercontent.com/59682162/115962066-ae43c180-a543-11eb-8143-44528a1c821c.png)

2. Fix Cmd and aLT Keys Swapped 
You only need to change the cmd and alt keys as shown in the picture
![gambar](https://user-images.githubusercontent.com/59682162/115961997-63c24500-a543-11eb-8808-70c41f662962.png)

Sorry For my bad english
