### ISSUE TITLE
Getting the latest beta

### ISSUE THREAD

**Issue by smartass08** [xkhoir/Lenovo-310-14ISK-Hackintosh-EFI-OpenCore#4]
Can you please elaborate the process regarding to download latest beta (11.4) using macrecover.py ?

**Comment by xkhoir** [comment]
1. You must install the non beta version first
(The beta version can only be downloaded via the macos software update. cannot be downloaded with macrecovery.py)

2. Then you must join the apple beta program at this link https://beta.apple.com/sp/betaprogram/enroll#macos

3. Follow the directions to install the utility

And boom you get a beta update notification !! :)

![gambar](https://user-images.githubusercontent.com/59682162/117098338-5ead9300-ad98-11eb-9dff-06c339801341.png)

sorry about my bad English
