### ISSUE TITLE
Patching Battery

### ISSUE THREAD

**Issue by rogerzero** [xkhoir/Lenovo-310-14ISK-Hackintosh-EFI-OpenCore#5]
I have the same hardware and bios version with yours, but my battery percentage is not work out.
I try to patch with the tutorial you post, I cannot apply some of your patch code. 

For example:

> into device label EC0 code_regex B1SN,\s+16, replace_matched begin BSN0,8,BSN1,8, end;
> into device label EC0 code_regex B1DV,\s+16, replace_matched begin BDV0,8,BDV1,8, end;
> into device label EC0 code_regex B1DC,\s+16, replace_matched begin BDC0,8,BDC1,8, end;
> into device label EC0 code_regex B1FC,\s+16, replace_matched begin BFC0,8,BFC1,8, end;

> into device label EC0 code_regex (FWBT,)\s+(64) replace_matched begin FWBX,%2,//%1%2 end;
> into device label EC0 code_regex (SMDA,)\s+(256) replace_matched begin SMDX,%2,//%1%2 end;
> into device label EC0 code_regex (BMN0,)\s+(72) replace_matched begin BMNX,%2,//%1%2 end;
> into device label EC0 code_regex (BDN0,)\s+(64) replace_matched begin BDNX,%2,//%1%2 end;

I don't know how to apply this code too

> B1B2(\_SB.PCI0.LPCB.EC0.BDC0,\_SB.PCI0.LPCB.EC0.BDC1)
> B1B2(\_SB.PCI0.LPCB.EC0.BFC0,\_SB.PCI0.LPCB.EC0.BFC1)
> B1B2(\_SB.PCI0.LPCB.EC0.BDV0,\_SB.PCI0.LPCB.EC0.BDV1)
> B1B2(\_SB.PCI0.LPCB.EC0.BSN0,\_SB.PCI0.LPCB.EC0.BSN1)

> FWBT -  \_SB.PCI0.LPCB.EC0.RECB(0X14,64)
> SMDA -  \_SB.PCI0.LPCB.EC0.RECB(0X64,256)
> BMN0 -  \_SB.PCI0.LPCB.EC0.RECB(0X8F,72)
> BDN0 -  \_SB.PCI0.LPCB.EC0.RECB(0X98,64)

Can you please help me?
Thank you so much

**Comment by xkhoir** [comment]
Hiii :)

1. If you are on the same "Lenovo IP310 14ISK" hardware,

--> try using my DSDT
--> or try using my EFI folder to boot the hackie

2. If you want to try it yourself in your EFI folder and it still doesn't work.

--> Make sure you are using the latest version of bios, virtual smc,and the SMCBatteryManager.kext plugin is already in the kext folder

Sorry mybad english
